"""Named scenario presets for the dashboard and comparison mode."""

from __future__ import annotations

from typing import Any

from .config import SimulationConfig


PRESET_SCENARIOS: dict[str, dict[str, Any]] = {
    "Balanced baseline": {
        "management_style": "neutral",
        "work_policy": "fixed schedule",
        "workload_intensity": 0.55,
        "deadline_pressure": 0.45,
        "autonomy_level": 0.55,
        "management_support": 0.55,
        "recognition_level": 0.50,
        "role_clarity": 0.60,
        "meeting_load": 0.40,
        "interruptions": 0.40,
        "conflict_level": 0.25,
        "psychological_safety": 0.55,
        "team_cohesion": 0.55,
    },
    "Supportive management + flexible schedule": {
        "management_style": "supportive",
        "work_policy": "flexible schedule",
        "workload_intensity": 0.50,
        "deadline_pressure": 0.38,
        "autonomy_level": 0.78,
        "management_support": 0.78,
        "recognition_level": 0.70,
        "role_clarity": 0.72,
        "meeting_load": 0.35,
        "interruptions": 0.28,
        "conflict_level": 0.16,
        "psychological_safety": 0.78,
        "sleep_quality": 0.70,
        "recovery_outside_work": 0.68,
        "team_cohesion": 0.72,
        "social_support_strength": 0.48,
    },
    "Supportive management + fixed schedule": {
        "management_style": "supportive",
        "work_policy": "fixed schedule",
        "workload_intensity": 0.52,
        "deadline_pressure": 0.40,
        "autonomy_level": 0.68,
        "management_support": 0.76,
        "recognition_level": 0.68,
        "role_clarity": 0.72,
        "meeting_load": 0.38,
        "interruptions": 0.34,
        "conflict_level": 0.17,
        "psychological_safety": 0.75,
        "team_cohesion": 0.68,
    },
    "Authoritarian management + fixed schedule": {
        "management_style": "authoritarian",
        "work_policy": "fixed schedule",
        "workload_intensity": 0.68,
        "deadline_pressure": 0.62,
        "autonomy_level": 0.30,
        "management_support": 0.32,
        "recognition_level": 0.34,
        "role_clarity": 0.55,
        "meeting_load": 0.52,
        "interruptions": 0.50,
        "conflict_level": 0.48,
        "psychological_safety": 0.32,
        "team_cohesion": 0.38,
    },
    "Authoritarian management + overtime": {
        "management_style": "authoritarian",
        "work_policy": "overtime-heavy",
        "workload_intensity": 0.82,
        "deadline_pressure": 0.78,
        "autonomy_level": 0.24,
        "management_support": 0.28,
        "recognition_level": 0.30,
        "role_clarity": 0.48,
        "meeting_load": 0.56,
        "interruptions": 0.54,
        "conflict_level": 0.56,
        "psychological_safety": 0.26,
        "team_cohesion": 0.34,
        "turnover_probability_above_threshold": 0.020,
    },
    "High-pressure startup": {
        "management_style": "chaotic",
        "work_policy": "overtime-heavy",
        "workload_intensity": 0.86,
        "deadline_pressure": 0.84,
        "autonomy_level": 0.64,
        "management_support": 0.44,
        "recognition_level": 0.55,
        "role_clarity": 0.38,
        "meeting_load": 0.62,
        "interruptions": 0.66,
        "conflict_level": 0.42,
        "psychological_safety": 0.44,
        "team_cohesion": 0.58,
        "probability_deadline_crunch": 0.060,
        "event_impact_strength": 0.32,
    },
    "Stable corporate environment": {
        "management_style": "neutral",
        "work_policy": "fixed schedule",
        "workload_intensity": 0.48,
        "deadline_pressure": 0.36,
        "autonomy_level": 0.54,
        "management_support": 0.62,
        "recognition_level": 0.56,
        "role_clarity": 0.78,
        "meeting_load": 0.45,
        "interruptions": 0.30,
        "conflict_level": 0.18,
        "psychological_safety": 0.64,
        "team_cohesion": 0.58,
        "probability_organizational_crisis": 0.010,
    },
    "Remote-friendly environment": {
        "management_style": "supportive",
        "work_policy": "remote/hybrid",
        "workload_intensity": 0.52,
        "deadline_pressure": 0.42,
        "autonomy_level": 0.76,
        "management_support": 0.70,
        "recognition_level": 0.62,
        "role_clarity": 0.68,
        "meeting_load": 0.46,
        "interruptions": 0.34,
        "conflict_level": 0.18,
        "psychological_safety": 0.72,
        "commute_duration_impact": 0.14,
        "team_cohesion": 0.60,
    },
    "Toxic workplace": {
        "management_style": "chaotic",
        "work_policy": "overtime-heavy",
        "workload_intensity": 0.90,
        "deadline_pressure": 0.86,
        "autonomy_level": 0.20,
        "management_support": 0.18,
        "recognition_level": 0.18,
        "role_clarity": 0.26,
        "meeting_load": 0.68,
        "interruptions": 0.72,
        "conflict_level": 0.82,
        "psychological_safety": 0.16,
        "team_cohesion": 0.22,
        "emotional_contagion_strength": 0.40,
        "conflict_propagation_strength": 0.50,
        "probability_organizational_crisis": 0.045,
        "probability_deadline_crunch": 0.060,
        "turnover_probability_above_threshold": 0.028,
        "event_impact_strength": 0.35,
    },
}


def get_scenario_config(name: str, base_config: SimulationConfig | None = None) -> SimulationConfig:
    base = base_config or SimulationConfig()
    overrides = PRESET_SCENARIOS.get(name, PRESET_SCENARIOS["Balanced baseline"]).copy()
    overrides["scenario_name"] = name
    return base.with_overrides(**overrides)
